# Generated by Django 4.2.6 on 2024-02-02 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductMedia',
        ),
    ]
